export const ROUTES = {
  landing: "/",
  login: "/login",
  signup: "/signup",
  admin: {
    root: "/admin",
    dashboard: "/admin/dashboard",
    courses: "/admin/courses",
    courseCreate: "/admin/courses/create",
    courseEdit: (id: string) => `/admin/courses/${id}/edit`,
    batches: "/admin/batches",
    batchCreate: "/admin/batches/create",
    batchDetail: (id: string) => `/admin/batches/${id}`,
    instructors: "/admin/users/instructors",
    students: "/admin/users/students",
    studentDetail: (id: string) => `/admin/users/students/${id}`,
    enrollments: "/admin/enrollments",
    batchOps: "/admin/batch-ops",
    certificates: "/admin/certificates",
    payments: "/admin/payments",
    paymentSettings: "/admin/payment-settings",
    catalogue: "/admin/catalogue",
  },
  instructor: {
    dashboard: "/instructor/dashboard",
  },
  student: {
    profile: "/portal/profile",
    explore: "/portal/explore",
    courseDetails: (id: string) => `/portal/explore/${id}`,
    batchSelect: (id: string) => `/portal/explore/${id}/batches`,
    myCourses: "/portal/my-courses",
    batchWorkspace: (id: string) => `/portal/my-courses/${id}`,
    selfPaced: (id: string) => `/portal/courses/${id}`,
    // Alias kept so old links / the role-guard fallback resolve.
    dashboard: "/portal/my-courses",
  },
} as const;
